export const HEMOCENTROS = [
  {
    id: 'recife',
    nome: 'Hemocentro Coordenador Recife',
    endereco: 'Rua Joaquim Nabuco, 171 - Graças',
    fone: '(81) 3183-8400',
    latitude: -8.0528651,
    longitude: -34.9074988,
  },
  {
    id: 'caruaru',
    nome: 'Hemocentro Regional Caruaru',
    endereco: 'Av. Oswaldo Cruz s/nº - Maurício de Nassau',
    fone: '(81) 3719.9565',
    latitude: -8.2764,
    longitude: -35.9723,
  },
  {
    id: 'garanhuns',
    nome: 'Hemocentro Regional Garanhuns',
    endereco: 'Rua Gonçalves Maia, s/nº Heliópolis',
    fone: '(87) 3761.2910',
    latitude: -8.8856,
    longitude: -36.4828,
  },
  {
    id: 'serra_talhada',
    nome: 'Hemocentro Regional Serra Talhada',
    endereco: 'Rua Joaquim Godoy s/nº Centro',
    fone: '(87) 3831-9321',
    latitude: -7.9906,
    longitude: -38.2987,
  },
  {
    id: 'petrolina',
    nome: 'Hemocentro Regional Petrolina',
    endereco: 'Rua Pacífico da Luz, s/nº - Centro',
    fone: '(87) 3866.6601',
    latitude: -9.3992,
    longitude: -40.5019,
  },
  {
    id: 'ouricuri',
    nome: 'Hemocentro Regional Ouricuri',
    endereco: 'Rua Ulisses Guimarães s/nº - Centro',
    fone: '',
    latitude: -7.8814,
    longitude: -40.0817,
  },
  {
    id: 'palmares',
    nome: 'Hemocentro Regional Palmares',
    endereco: 'Funcionando temporariamente no Hospital Regional de Palmares',
    obs: 'Esta Unidade está desativada para coleta, funcionando temporariamente como Agência Transfusional.',
    fone: '',
    latitude: -8.6833,
    longitude: -35.5833,
  },
  {
    id: 'arcoverde',
    nome: 'Núcleo de Hemoterapia Regional Arcoverde',
    endereco: 'Av. Joaquim Nabuco, s/nº - São Cristovão',
    fone: '(87) 3821.8550',
    latitude: -8.4177,
    longitude: -37.0617,
  },
  {
    id: 'salgueiro',
    nome: 'Núcleo de Hemoterapia Regional Salgueiro',
    endereco: 'Rua Joaquim Gondim, 65 - Stº Antônio',
    fone: '(87) 3871.8569',
    latitude: -8.0745,
    longitude: -39.1197,
  },
  {
    id: 'limoeiro',
    nome: 'Agência Transfusional Regional Limoeiro',
    endereco: 'Rua Santa Terezinha, 174 - José Fernandes Salsa',
    fone: '(81) 3628.8806',
    latitude: -7.8744,
    longitude: -35.4503,
  },
];

export const HORARIO_FUNCIONAMENTO = '07:30 as 17h adm e doação das 07:15 as 18:30';
